/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TakeoffLoginRouteImport } from './routes/takeoff-login'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsPrecedenceRouteImport } from './routes/products.precedence'
import { Route as ProductsStyleguardRouteImport } from './routes/products.styleguard'
import { Route as ProductsStyleviewRouteImport } from './routes/products.styleview'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAppAiRouteImport } from './routes/_authenticated/app.ai'
import { Route as AuthenticatedAppAiMemoryRouteImport } from './routes/_authenticated/app.ai-memory'
import { Route as AuthenticatedAppAiSettingsRouteImport } from './routes/_authenticated/app.ai-settings'
import { Route as AuthenticatedAppBidsRouteImport } from './routes/_authenticated/app.bids'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/app.dashboard'
import { Route as AuthenticatedAppIncomingFilesRouteImport } from './routes/_authenticated/app.incoming-files'
import { Route as AuthenticatedAppJurisdictionRouteImport } from './routes/_authenticated/app.jurisdiction'
import { Route as AuthenticatedAppPagesRouteImport } from './routes/_authenticated/app.pages'
import { Route as AuthenticatedAppQuoteRequestsRouteImport } from './routes/_authenticated/app.quote-requests'
import { Route as AuthenticatedAppRecycleBinRouteImport } from './routes/_authenticated/app.recycle-bin'
import { Route as AuthenticatedAppSchedulesRouteImport } from './routes/_authenticated/app.schedules'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppSiteRouteImport } from './routes/_authenticated/app.site'
import { Route as AuthenticatedAppTakeoffRouteImport } from './routes/_authenticated/app.takeoff'
import { Route as AuthenticatedAppViewerRouteImport } from './routes/_authenticated/app.viewer'
import { Route as AuthenticatedAppYkkAutomationRouteImport } from './routes/_authenticated/app.ykk-automation'
import { Route as AuthenticatedAppYkkIntegrationRouteImport } from './routes/_authenticated/app.ykk-integration'
import { Route as OauthDropboxReturnRouteImport } from './routes/oauth.dropbox.return'
import { Route as OauthGoogleReturnRouteImport } from './routes/oauth.google.return'
import { Route as AuthenticatedAppProjectsIndexRouteImport } from './routes/_authenticated/app.projects.index'
import { Route as AuthenticatedAppProjectsProjectIdRouteImport } from './routes/_authenticated/app.projects.$projectId'
import { Route as AuthenticatedAppSiteAiRouteImport } from './routes/_authenticated/app.site.ai'
import { Route as AuthenticatedAppTakeoffIndexRouteImport } from './routes/_authenticated/app.takeoff.index'
import { Route as AuthenticatedAppTakeoffCompleteRouteImport } from './routes/_authenticated/app.takeoff.complete'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TakeoffLoginRoute = TakeoffLoginRouteImport.update({
  id: '/takeoff-login',
  path: '/takeoff-login',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsPrecedenceRoute = ProductsPrecedenceRouteImport.update({
  id: '/products/precedence',
  path: '/products/precedence',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsStyleguardRoute = ProductsStyleguardRouteImport.update({
  id: '/products/styleguard',
  path: '/products/styleguard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsStyleviewRoute = ProductsStyleviewRouteImport.update({
  id: '/products/styleview',
  path: '/products/styleview',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppAiRoute = AuthenticatedAppAiRouteImport.update({
  id: '/app/ai',
  path: '/app/ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAiMemoryRoute =
  AuthenticatedAppAiMemoryRouteImport.update({
    id: '/app/ai-memory',
    path: '/app/ai-memory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAiSettingsRoute =
  AuthenticatedAppAiSettingsRouteImport.update({
    id: '/app/ai-settings',
    path: '/app/ai-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppBidsRoute = AuthenticatedAppBidsRouteImport.update({
  id: '/app/bids',
  path: '/app/bids',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/app/dashboard',
    path: '/app/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppIncomingFilesRoute =
  AuthenticatedAppIncomingFilesRouteImport.update({
    id: '/app/incoming-files',
    path: '/app/incoming-files',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppJurisdictionRoute =
  AuthenticatedAppJurisdictionRouteImport.update({
    id: '/app/jurisdiction',
    path: '/app/jurisdiction',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppPagesRoute = AuthenticatedAppPagesRouteImport.update({
  id: '/app/pages',
  path: '/app/pages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppQuoteRequestsRoute =
  AuthenticatedAppQuoteRequestsRouteImport.update({
    id: '/app/quote-requests',
    path: '/app/quote-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRecycleBinRoute =
  AuthenticatedAppRecycleBinRouteImport.update({
    id: '/app/recycle-bin',
    path: '/app/recycle-bin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSchedulesRoute =
  AuthenticatedAppSchedulesRouteImport.update({
    id: '/app/schedules',
    path: '/app/schedules',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/app/settings',
    path: '/app/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSiteRoute = AuthenticatedAppSiteRouteImport.update({
  id: '/app/site',
  path: '/app/site',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppTakeoffRoute = AuthenticatedAppTakeoffRouteImport.update({
  id: '/app/takeoff',
  path: '/app/takeoff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppViewerRoute = AuthenticatedAppViewerRouteImport.update({
  id: '/app/viewer',
  path: '/app/viewer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppYkkAutomationRoute =
  AuthenticatedAppYkkAutomationRouteImport.update({
    id: '/app/ykk-automation',
    path: '/app/ykk-automation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppYkkIntegrationRoute =
  AuthenticatedAppYkkIntegrationRouteImport.update({
    id: '/app/ykk-integration',
    path: '/app/ykk-integration',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const OauthDropboxReturnRoute = OauthDropboxReturnRouteImport.update({
  id: '/oauth/dropbox/return',
  path: '/oauth/dropbox/return',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthGoogleReturnRoute = OauthGoogleReturnRouteImport.update({
  id: '/oauth/google/return',
  path: '/oauth/google/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppProjectsIndexRoute =
  AuthenticatedAppProjectsIndexRouteImport.update({
    id: '/app/projects/',
    path: '/app/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppProjectsProjectIdRoute =
  AuthenticatedAppProjectsProjectIdRouteImport.update({
    id: '/app/projects/$projectId',
    path: '/app/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppSiteAiRoute = AuthenticatedAppSiteAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAppSiteRoute,
} as any)
const AuthenticatedAppTakeoffIndexRoute =
  AuthenticatedAppTakeoffIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppTakeoffRoute,
  } as any)
const AuthenticatedAppTakeoffCompleteRoute =
  AuthenticatedAppTakeoffCompleteRouteImport.update({
    id: '/complete',
    path: '/complete',
    getParentRoute: () => AuthenticatedAppTakeoffRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/takeoff-login': typeof TakeoffLoginRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/products/precedence': typeof ProductsPrecedenceRoute
  '/products/styleguard': typeof ProductsStyleguardRoute
  '/products/styleview': typeof ProductsStyleviewRoute
  '/products/': typeof ProductsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/ai': typeof AuthenticatedAppAiRoute
  '/app/ai-memory': typeof AuthenticatedAppAiMemoryRoute
  '/app/ai-settings': typeof AuthenticatedAppAiSettingsRoute
  '/app/bids': typeof AuthenticatedAppBidsRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/incoming-files': typeof AuthenticatedAppIncomingFilesRoute
  '/app/jurisdiction': typeof AuthenticatedAppJurisdictionRoute
  '/app/pages': typeof AuthenticatedAppPagesRoute
  '/app/quote-requests': typeof AuthenticatedAppQuoteRequestsRoute
  '/app/recycle-bin': typeof AuthenticatedAppRecycleBinRoute
  '/app/schedules': typeof AuthenticatedAppSchedulesRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/site': typeof AuthenticatedAppSiteRouteWithChildren
  '/app/takeoff': typeof AuthenticatedAppTakeoffRouteWithChildren
  '/app/viewer': typeof AuthenticatedAppViewerRoute
  '/app/ykk-automation': typeof AuthenticatedAppYkkAutomationRoute
  '/app/ykk-integration': typeof AuthenticatedAppYkkIntegrationRoute
  '/oauth/dropbox/return': typeof OauthDropboxReturnRoute
  '/oauth/google/return': typeof OauthGoogleReturnRoute
  '/app/projects/$projectId': typeof AuthenticatedAppProjectsProjectIdRoute
  '/app/site/ai': typeof AuthenticatedAppSiteAiRoute
  '/app/takeoff/complete': typeof AuthenticatedAppTakeoffCompleteRoute
  '/app/projects/': typeof AuthenticatedAppProjectsIndexRoute
  '/app/takeoff/': typeof AuthenticatedAppTakeoffIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/takeoff-login': typeof TakeoffLoginRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/products/precedence': typeof ProductsPrecedenceRoute
  '/products/styleguard': typeof ProductsStyleguardRoute
  '/products/styleview': typeof ProductsStyleviewRoute
  '/products': typeof ProductsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/ai': typeof AuthenticatedAppAiRoute
  '/app/ai-memory': typeof AuthenticatedAppAiMemoryRoute
  '/app/ai-settings': typeof AuthenticatedAppAiSettingsRoute
  '/app/bids': typeof AuthenticatedAppBidsRoute
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/incoming-files': typeof AuthenticatedAppIncomingFilesRoute
  '/app/jurisdiction': typeof AuthenticatedAppJurisdictionRoute
  '/app/pages': typeof AuthenticatedAppPagesRoute
  '/app/quote-requests': typeof AuthenticatedAppQuoteRequestsRoute
  '/app/recycle-bin': typeof AuthenticatedAppRecycleBinRoute
  '/app/schedules': typeof AuthenticatedAppSchedulesRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/site': typeof AuthenticatedAppSiteRouteWithChildren
  '/app/viewer': typeof AuthenticatedAppViewerRoute
  '/app/ykk-automation': typeof AuthenticatedAppYkkAutomationRoute
  '/app/ykk-integration': typeof AuthenticatedAppYkkIntegrationRoute
  '/oauth/dropbox/return': typeof OauthDropboxReturnRoute
  '/oauth/google/return': typeof OauthGoogleReturnRoute
  '/app/projects/$projectId': typeof AuthenticatedAppProjectsProjectIdRoute
  '/app/site/ai': typeof AuthenticatedAppSiteAiRoute
  '/app/takeoff/complete': typeof AuthenticatedAppTakeoffCompleteRoute
  '/app/projects': typeof AuthenticatedAppProjectsIndexRoute
  '/app/takeoff': typeof AuthenticatedAppTakeoffIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/takeoff-login': typeof TakeoffLoginRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/products/precedence': typeof ProductsPrecedenceRoute
  '/products/styleguard': typeof ProductsStyleguardRoute
  '/products/styleview': typeof ProductsStyleviewRoute
  '/products/': typeof ProductsIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/app/ai': typeof AuthenticatedAppAiRoute
  '/_authenticated/app/ai-memory': typeof AuthenticatedAppAiMemoryRoute
  '/_authenticated/app/ai-settings': typeof AuthenticatedAppAiSettingsRoute
  '/_authenticated/app/bids': typeof AuthenticatedAppBidsRoute
  '/_authenticated/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/app/incoming-files': typeof AuthenticatedAppIncomingFilesRoute
  '/_authenticated/app/jurisdiction': typeof AuthenticatedAppJurisdictionRoute
  '/_authenticated/app/pages': typeof AuthenticatedAppPagesRoute
  '/_authenticated/app/quote-requests': typeof AuthenticatedAppQuoteRequestsRoute
  '/_authenticated/app/recycle-bin': typeof AuthenticatedAppRecycleBinRoute
  '/_authenticated/app/schedules': typeof AuthenticatedAppSchedulesRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/site': typeof AuthenticatedAppSiteRouteWithChildren
  '/_authenticated/app/takeoff': typeof AuthenticatedAppTakeoffRouteWithChildren
  '/_authenticated/app/viewer': typeof AuthenticatedAppViewerRoute
  '/_authenticated/app/ykk-automation': typeof AuthenticatedAppYkkAutomationRoute
  '/_authenticated/app/ykk-integration': typeof AuthenticatedAppYkkIntegrationRoute
  '/oauth/dropbox/return': typeof OauthDropboxReturnRoute
  '/oauth/google/return': typeof OauthGoogleReturnRoute
  '/_authenticated/app/projects/$projectId': typeof AuthenticatedAppProjectsProjectIdRoute
  '/_authenticated/app/site/ai': typeof AuthenticatedAppSiteAiRoute
  '/_authenticated/app/takeoff/complete': typeof AuthenticatedAppTakeoffCompleteRoute
  '/_authenticated/app/projects/': typeof AuthenticatedAppProjectsIndexRoute
  '/_authenticated/app/takeoff/': typeof AuthenticatedAppTakeoffIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/mcp'
    | '/privacy'
    | '/reset-password'
    | '/resources'
    | '/sitemap.xml'
    | '/takeoff-login'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/products/precedence'
    | '/products/styleguard'
    | '/products/styleview'
    | '/products/'
    | '/.mcp/invoke-tool/$tool'
    | '/app/ai'
    | '/app/ai-memory'
    | '/app/ai-settings'
    | '/app/bids'
    | '/app/dashboard'
    | '/app/incoming-files'
    | '/app/jurisdiction'
    | '/app/pages'
    | '/app/quote-requests'
    | '/app/recycle-bin'
    | '/app/schedules'
    | '/app/settings'
    | '/app/site'
    | '/app/takeoff'
    | '/app/viewer'
    | '/app/ykk-automation'
    | '/app/ykk-integration'
    | '/oauth/dropbox/return'
    | '/oauth/google/return'
    | '/app/projects/$projectId'
    | '/app/site/ai'
    | '/app/takeoff/complete'
    | '/app/projects/'
    | '/app/takeoff/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/mcp'
    | '/privacy'
    | '/reset-password'
    | '/resources'
    | '/sitemap.xml'
    | '/takeoff-login'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/products/precedence'
    | '/products/styleguard'
    | '/products/styleview'
    | '/products'
    | '/.mcp/invoke-tool/$tool'
    | '/app/ai'
    | '/app/ai-memory'
    | '/app/ai-settings'
    | '/app/bids'
    | '/app/dashboard'
    | '/app/incoming-files'
    | '/app/jurisdiction'
    | '/app/pages'
    | '/app/quote-requests'
    | '/app/recycle-bin'
    | '/app/schedules'
    | '/app/settings'
    | '/app/site'
    | '/app/viewer'
    | '/app/ykk-automation'
    | '/app/ykk-integration'
    | '/oauth/dropbox/return'
    | '/oauth/google/return'
    | '/app/projects/$projectId'
    | '/app/site/ai'
    | '/app/takeoff/complete'
    | '/app/projects'
    | '/app/takeoff'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/mcp'
    | '/privacy'
    | '/reset-password'
    | '/resources'
    | '/sitemap.xml'
    | '/takeoff-login'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/products/precedence'
    | '/products/styleguard'
    | '/products/styleview'
    | '/products/'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/app/ai'
    | '/_authenticated/app/ai-memory'
    | '/_authenticated/app/ai-settings'
    | '/_authenticated/app/bids'
    | '/_authenticated/app/dashboard'
    | '/_authenticated/app/incoming-files'
    | '/_authenticated/app/jurisdiction'
    | '/_authenticated/app/pages'
    | '/_authenticated/app/quote-requests'
    | '/_authenticated/app/recycle-bin'
    | '/_authenticated/app/schedules'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/site'
    | '/_authenticated/app/takeoff'
    | '/_authenticated/app/viewer'
    | '/_authenticated/app/ykk-automation'
    | '/_authenticated/app/ykk-integration'
    | '/oauth/dropbox/return'
    | '/oauth/google/return'
    | '/_authenticated/app/projects/$projectId'
    | '/_authenticated/app/site/ai'
    | '/_authenticated/app/takeoff/complete'
    | '/_authenticated/app/projects/'
    | '/_authenticated/app/takeoff/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  McpRoute: typeof McpRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TakeoffLoginRoute: typeof TakeoffLoginRoute
  TermsRoute: typeof TermsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ProductsPrecedenceRoute: typeof ProductsPrecedenceRoute
  ProductsStyleguardRoute: typeof ProductsStyleguardRoute
  ProductsStyleviewRoute: typeof ProductsStyleviewRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  OauthDropboxReturnRoute: typeof OauthDropboxReturnRoute
  OauthGoogleReturnRoute: typeof OauthGoogleReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/takeoff-login': {
      id: '/takeoff-login'
      path: '/takeoff-login'
      fullPath: '/takeoff-login'
      preLoaderRoute: typeof TakeoffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/precedence': {
      id: '/products/precedence'
      path: '/products/precedence'
      fullPath: '/products/precedence'
      preLoaderRoute: typeof ProductsPrecedenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/styleguard': {
      id: '/products/styleguard'
      path: '/products/styleguard'
      fullPath: '/products/styleguard'
      preLoaderRoute: typeof ProductsStyleguardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/styleview': {
      id: '/products/styleview'
      path: '/products/styleview'
      fullPath: '/products/styleview'
      preLoaderRoute: typeof ProductsStyleviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/ai': {
      id: '/_authenticated/app/ai'
      path: '/app/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AuthenticatedAppAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/ai-memory': {
      id: '/_authenticated/app/ai-memory'
      path: '/app/ai-memory'
      fullPath: '/app/ai-memory'
      preLoaderRoute: typeof AuthenticatedAppAiMemoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/ai-settings': {
      id: '/_authenticated/app/ai-settings'
      path: '/app/ai-settings'
      fullPath: '/app/ai-settings'
      preLoaderRoute: typeof AuthenticatedAppAiSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/bids': {
      id: '/_authenticated/app/bids'
      path: '/app/bids'
      fullPath: '/app/bids'
      preLoaderRoute: typeof AuthenticatedAppBidsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/dashboard': {
      id: '/_authenticated/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/incoming-files': {
      id: '/_authenticated/app/incoming-files'
      path: '/app/incoming-files'
      fullPath: '/app/incoming-files'
      preLoaderRoute: typeof AuthenticatedAppIncomingFilesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/jurisdiction': {
      id: '/_authenticated/app/jurisdiction'
      path: '/app/jurisdiction'
      fullPath: '/app/jurisdiction'
      preLoaderRoute: typeof AuthenticatedAppJurisdictionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/pages': {
      id: '/_authenticated/app/pages'
      path: '/app/pages'
      fullPath: '/app/pages'
      preLoaderRoute: typeof AuthenticatedAppPagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/quote-requests': {
      id: '/_authenticated/app/quote-requests'
      path: '/app/quote-requests'
      fullPath: '/app/quote-requests'
      preLoaderRoute: typeof AuthenticatedAppQuoteRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/recycle-bin': {
      id: '/_authenticated/app/recycle-bin'
      path: '/app/recycle-bin'
      fullPath: '/app/recycle-bin'
      preLoaderRoute: typeof AuthenticatedAppRecycleBinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/schedules': {
      id: '/_authenticated/app/schedules'
      path: '/app/schedules'
      fullPath: '/app/schedules'
      preLoaderRoute: typeof AuthenticatedAppSchedulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/site': {
      id: '/_authenticated/app/site'
      path: '/app/site'
      fullPath: '/app/site'
      preLoaderRoute: typeof AuthenticatedAppSiteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/takeoff': {
      id: '/_authenticated/app/takeoff'
      path: '/app/takeoff'
      fullPath: '/app/takeoff'
      preLoaderRoute: typeof AuthenticatedAppTakeoffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/viewer': {
      id: '/_authenticated/app/viewer'
      path: '/app/viewer'
      fullPath: '/app/viewer'
      preLoaderRoute: typeof AuthenticatedAppViewerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/ykk-automation': {
      id: '/_authenticated/app/ykk-automation'
      path: '/app/ykk-automation'
      fullPath: '/app/ykk-automation'
      preLoaderRoute: typeof AuthenticatedAppYkkAutomationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/ykk-integration': {
      id: '/_authenticated/app/ykk-integration'
      path: '/app/ykk-integration'
      fullPath: '/app/ykk-integration'
      preLoaderRoute: typeof AuthenticatedAppYkkIntegrationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/oauth/dropbox/return': {
      id: '/oauth/dropbox/return'
      path: '/oauth/dropbox/return'
      fullPath: '/oauth/dropbox/return'
      preLoaderRoute: typeof OauthDropboxReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/google/return': {
      id: '/oauth/google/return'
      path: '/oauth/google/return'
      fullPath: '/oauth/google/return'
      preLoaderRoute: typeof OauthGoogleReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/projects/': {
      id: '/_authenticated/app/projects/'
      path: '/app/projects'
      fullPath: '/app/projects/'
      preLoaderRoute: typeof AuthenticatedAppProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/projects/$projectId': {
      id: '/_authenticated/app/projects/$projectId'
      path: '/app/projects/$projectId'
      fullPath: '/app/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedAppProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/site/ai': {
      id: '/_authenticated/app/site/ai'
      path: '/ai'
      fullPath: '/app/site/ai'
      preLoaderRoute: typeof AuthenticatedAppSiteAiRouteImport
      parentRoute: typeof AuthenticatedAppSiteRoute
    }
    '/_authenticated/app/takeoff/': {
      id: '/_authenticated/app/takeoff/'
      path: '/'
      fullPath: '/app/takeoff/'
      preLoaderRoute: typeof AuthenticatedAppTakeoffIndexRouteImport
      parentRoute: typeof AuthenticatedAppTakeoffRoute
    }
    '/_authenticated/app/takeoff/complete': {
      id: '/_authenticated/app/takeoff/complete'
      path: '/complete'
      fullPath: '/app/takeoff/complete'
      preLoaderRoute: typeof AuthenticatedAppTakeoffCompleteRouteImport
      parentRoute: typeof AuthenticatedAppTakeoffRoute
    }
  }
}

interface AuthenticatedAppSiteRouteChildren {
  AuthenticatedAppSiteAiRoute: typeof AuthenticatedAppSiteAiRoute
}

const AuthenticatedAppSiteRouteChildren: AuthenticatedAppSiteRouteChildren = {
  AuthenticatedAppSiteAiRoute: AuthenticatedAppSiteAiRoute,
}

const AuthenticatedAppSiteRouteWithChildren =
  AuthenticatedAppSiteRoute._addFileChildren(AuthenticatedAppSiteRouteChildren)

interface AuthenticatedAppTakeoffRouteChildren {
  AuthenticatedAppTakeoffCompleteRoute: typeof AuthenticatedAppTakeoffCompleteRoute
  AuthenticatedAppTakeoffIndexRoute: typeof AuthenticatedAppTakeoffIndexRoute
}

const AuthenticatedAppTakeoffRouteChildren: AuthenticatedAppTakeoffRouteChildren =
  {
    AuthenticatedAppTakeoffCompleteRoute: AuthenticatedAppTakeoffCompleteRoute,
    AuthenticatedAppTakeoffIndexRoute: AuthenticatedAppTakeoffIndexRoute,
  }

const AuthenticatedAppTakeoffRouteWithChildren =
  AuthenticatedAppTakeoffRoute._addFileChildren(
    AuthenticatedAppTakeoffRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppAiRoute: typeof AuthenticatedAppAiRoute
  AuthenticatedAppAiMemoryRoute: typeof AuthenticatedAppAiMemoryRoute
  AuthenticatedAppAiSettingsRoute: typeof AuthenticatedAppAiSettingsRoute
  AuthenticatedAppBidsRoute: typeof AuthenticatedAppBidsRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppIncomingFilesRoute: typeof AuthenticatedAppIncomingFilesRoute
  AuthenticatedAppJurisdictionRoute: typeof AuthenticatedAppJurisdictionRoute
  AuthenticatedAppPagesRoute: typeof AuthenticatedAppPagesRoute
  AuthenticatedAppQuoteRequestsRoute: typeof AuthenticatedAppQuoteRequestsRoute
  AuthenticatedAppRecycleBinRoute: typeof AuthenticatedAppRecycleBinRoute
  AuthenticatedAppSchedulesRoute: typeof AuthenticatedAppSchedulesRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppSiteRoute: typeof AuthenticatedAppSiteRouteWithChildren
  AuthenticatedAppTakeoffRoute: typeof AuthenticatedAppTakeoffRouteWithChildren
  AuthenticatedAppViewerRoute: typeof AuthenticatedAppViewerRoute
  AuthenticatedAppYkkAutomationRoute: typeof AuthenticatedAppYkkAutomationRoute
  AuthenticatedAppYkkIntegrationRoute: typeof AuthenticatedAppYkkIntegrationRoute
  AuthenticatedAppProjectsProjectIdRoute: typeof AuthenticatedAppProjectsProjectIdRoute
  AuthenticatedAppProjectsIndexRoute: typeof AuthenticatedAppProjectsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppAiRoute: AuthenticatedAppAiRoute,
  AuthenticatedAppAiMemoryRoute: AuthenticatedAppAiMemoryRoute,
  AuthenticatedAppAiSettingsRoute: AuthenticatedAppAiSettingsRoute,
  AuthenticatedAppBidsRoute: AuthenticatedAppBidsRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppIncomingFilesRoute: AuthenticatedAppIncomingFilesRoute,
  AuthenticatedAppJurisdictionRoute: AuthenticatedAppJurisdictionRoute,
  AuthenticatedAppPagesRoute: AuthenticatedAppPagesRoute,
  AuthenticatedAppQuoteRequestsRoute: AuthenticatedAppQuoteRequestsRoute,
  AuthenticatedAppRecycleBinRoute: AuthenticatedAppRecycleBinRoute,
  AuthenticatedAppSchedulesRoute: AuthenticatedAppSchedulesRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppSiteRoute: AuthenticatedAppSiteRouteWithChildren,
  AuthenticatedAppTakeoffRoute: AuthenticatedAppTakeoffRouteWithChildren,
  AuthenticatedAppViewerRoute: AuthenticatedAppViewerRoute,
  AuthenticatedAppYkkAutomationRoute: AuthenticatedAppYkkAutomationRoute,
  AuthenticatedAppYkkIntegrationRoute: AuthenticatedAppYkkIntegrationRoute,
  AuthenticatedAppProjectsProjectIdRoute:
    AuthenticatedAppProjectsProjectIdRoute,
  AuthenticatedAppProjectsIndexRoute: AuthenticatedAppProjectsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  McpRoute: McpRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TakeoffLoginRoute: TakeoffLoginRoute,
  TermsRoute: TermsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ProductsPrecedenceRoute: ProductsPrecedenceRoute,
  ProductsStyleguardRoute: ProductsStyleguardRoute,
  ProductsStyleviewRoute: ProductsStyleviewRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  OauthDropboxReturnRoute: OauthDropboxReturnRoute,
  OauthGoogleReturnRoute: OauthGoogleReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
