// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Add VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY to your .env file.`;
    console.warn(`[Supabase] ${message} Using local development demo auth.`);
    if (import.meta.env.DEV) {
      const demoUser = {
        id: "awm-local-demo",
        email: "demo@awm.local",
        aud: "authenticated",
        role: "authenticated",
      };
      const demoSession = {
        access_token: "awm-local-demo-token",
        refresh_token: "",
        user: demoUser,
      };
      // Demo-mode table stub: every query resolves to empty data so pages render
      // with zero counts instead of crashing when Supabase isn't connected.
      const demoQueryResult = { data: [], error: null, count: 0 };
      /** Minimal thenable query-builder surface mirroring the Supabase calls the app makes. */
      interface DemoQueryChain {
        select: (...args: unknown[]) => DemoQueryChain;
        insert: (...args: unknown[]) => DemoQueryChain;
        update: (...args: unknown[]) => DemoQueryChain;
        upsert: (...args: unknown[]) => DemoQueryChain;
        delete: (...args: unknown[]) => DemoQueryChain;
        eq: (...args: unknown[]) => DemoQueryChain;
        neq: (...args: unknown[]) => DemoQueryChain;
        is: (...args: unknown[]) => DemoQueryChain;
        in: (...args: unknown[]) => DemoQueryChain;
        order: (...args: unknown[]) => DemoQueryChain;
        limit: (...args: unknown[]) => DemoQueryChain;
        range: (...args: unknown[]) => DemoQueryChain;
        single: () => Promise<{ data: null; error: null }>;
        maybeSingle: () => Promise<{ data: null; error: null }>;
        then: (resolve: (value: unknown) => void) => void;
      }
      const makeChain = (): DemoQueryChain => {
        const chain: DemoQueryChain = {
          select: () => chain,
          insert: () => chain,
          update: () => chain,
          upsert: () => chain,
          delete: () => chain,
          eq: () => chain,
          neq: () => chain,
          is: () => chain,
          in: () => chain,
          order: () => chain,
          limit: () => chain,
          range: () => chain,
          single: async () => ({ data: null, error: null }),
          maybeSingle: async () => ({ data: null, error: null }),
          then: (resolve: (v: unknown) => void) => resolve(demoQueryResult),
        };
        return chain;
      };
      return {
        auth: {
          getUser: async () => ({ data: { user: demoUser }, error: null }),
          getSession: async () => ({ data: { session: demoSession }, error: null }),
          signInWithPassword: async () => ({
            data: { user: demoUser, session: demoSession },
            error: null,
          }),
          signOut: async () => ({ error: null }),
          resetPasswordForEmail: async () => ({ data: {}, error: null }),
          onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => undefined } } }),
        },
        from: () => makeChain(),
        storage: {
          from: () => ({
            upload: async () => ({ data: { path: "demo" }, error: null }),
            download: async () => ({ data: null, error: { message: "Demo mode: no storage" } }),
            list: async () => ({ data: [], error: null }),
            getPublicUrl: () => ({ data: { publicUrl: "" } }),
            remove: async () => ({ data: [], error: null }),
          }),
        },
      } as unknown as ReturnType<typeof createClient<Database>>;
    }
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
